export const imageData = {
  Черный: 'images/b/1.png',
  Черный1: 'images/b/2.png',
  Черный2: 'images/b/3.png',
  Черный3: 'images/b/4.png',
  Черный4: 'images/b/5.png',
  Черный5: 'images/b/6.png',
  Синий: 'images/s/1.png',
  Синий1: 'images/s/2.png',
  Синий2: 'images/s/3.png',
  Коричневый: 'images/k/1.png',
  Коричневый1: 'images/k/2.png',
  Коричневый2: 'images/k/3.png',
  Коричневый3: 'images/k/4.png',
  Коричневый4: 'images/k/5.png',
  Коричневый5: 'images/k/6.png',
  //Бордовый: 'images/b1.webp',
  //Бордовый1: 'images/brd.webp',
};
