export const imageData = {
  Черный: 'images/b/1.webp',
  Черный1: 'images/b/2.webp',
  Черный2: 'images/b/3.webp',
  Черный3: 'images/b/4.webp',
  Черный4: 'images/b/5.webp',
  Черный5: 'images/b/6.webp',
  Синий: 'images/s/1.webp',
  Синий1: 'images/s/2.webp',
  Синий2: 'images/s/3.webp',
  Коричневый: 'images/k/1.webp',
  Коричневый1: 'images/k/2.webp',
  Коричневый2: 'images/k/3.webp',
  Коричневый3: 'images/k/4.webp',
  Коричневый4: 'images/k/5.webp',
  Коричневый5: 'images/k/6.webp',
};
